# Домашнее задание к лекции "Библиотека numpy. Вычислительные задачи"

## Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
N = 10
np.arange(N-1, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
N = 10
a = np.diag(np.arange(N-1, -1, -1))
a

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
np.diagonal(a).sum()

45

## Задание 3

Решите систему уравнений:
```
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
```

In [5]:
# коэффициенты при переменных в левой части уравнения

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])

In [6]:
# значения в правой части уравнения

b = np.array([4, 12, -3])

In [7]:
from numpy import linalg

In [8]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [9]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

## Задание 4

В материалах занятия раздел “Задача 4 домашнего задания”

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

```from IPython.display import Image
Image("user_matrix.JPG")``` - не работает(

Матрица в виде numpy array

In [10]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [11]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [12]:
import matplotlib.pyplot as plt

In [13]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [14]:
user_number = 0
cosine_max = 0
a = next_user_stats
i = 0

for b in users_stats:
    i += 1
    if cosine(a, b) > cosine_max:
        cosine_max = cosine(a, b)
        user_number = i
        
print('Самый похожий пользователь: № ', user_number)

Самый похожий пользователь: №  8
